name: Build XMRDesk

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Install dependencies
      run: |
        vcpkg install libuv:x64-windows-static
        vcpkg integrate install

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: |
        cmake .. -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
          -DVCPKG_TARGET_TRIPLET=x64-windows-static ^
          -DWITH_QT_GUI=OFF ^
          -DWITH_HWLOC=OFF ^
          -DWITH_OPENCL=OFF ^
          -DWITH_CUDA=OFF ^
          -DWITH_RANDOMX=ON ^
          -DWITH_HTTP=ON ^
          -DWITH_TLS=OFF ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DBUILD_STATIC=ON

    - name: Build
      working-directory: build
      run: cmake --build . --config Release

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: xmrdesk-windows-x64
        path: build/Release/xmrdesk.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libuv1-dev qt6-base-dev qt6-charts-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DWITH_QT_GUI=ON \
          -DWITH_HWLOC=OFF \
          -DWITH_OPENCL=OFF \
          -DWITH_CUDA=OFF \
          -DWITH_RANDOMX=ON \
          -DWITH_HTTP=ON

    - name: Build
      working-directory: build
      run: make -j$(nproc)

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: xmrdesk-linux-x64
        path: build/xmrdesk