name: Windows Build Simple

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-windows-console:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Install vcpkg dependencies
      run: |
        vcpkg install libuv:x64-windows
        vcpkg integrate install

    - name: Build console version
      run: |
        mkdir build-console
        cd build-console
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DWITH_QT_GUI=OFF -DWITH_HWLOC=OFF -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_RANDOMX=ON -DWITH_HTTP=ON -DWITH_TLS=OFF -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Package console build
      run: |
        mkdir xmrdesk-console-release
        copy build-console\Release\xmrdesk.exe xmrdesk-console-release\
        copy README.md xmrdesk-console-release\
        copy LICENSE xmrdesk-console-release\
        copy start-console.bat xmrdesk-console-release\

    - name: Upload console artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrdesk-windows-console
        path: xmrdesk-console-release/

  build-windows-gui:
    runs-on: windows-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.*'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        cache: true
        setup-python: false

    - name: Install vcpkg dependencies
      run: |
        vcpkg install libuv:x64-windows
        vcpkg integrate install

    - name: Build GUI version
      run: |
        mkdir build-gui
        cd build-gui
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}" -DWITH_QT_GUI=ON -DWITH_HWLOC=OFF -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_RANDOMX=ON -DWITH_HTTP=ON -DWITH_TLS=OFF -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Deploy Qt6
      run: |
        cd build-gui\Release
        windeployqt.exe --release --no-translations --no-system-d3d-compiler xmrdesk.exe

    - name: Package GUI build
      run: |
        mkdir xmrdesk-gui-release
        robocopy build-gui\Release xmrdesk-gui-release /E /XF *.pdb *.ilk
        copy README.md xmrdesk-gui-release\
        copy LICENSE xmrdesk-gui-release\
        copy start.bat xmrdesk-gui-release\start-gui.bat
        copy start-console.bat xmrdesk-gui-release\

    - name: Upload GUI artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: xmrdesk-windows-gui
        path: xmrdesk-gui-release/